Exercise-1(Import the numpy package under the name np)

In [ ]:
import numpy as np

Exercise-2(Print the numpy version and the configuration)


In [ ]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

Exercise-3(Print the numpy version and the configuration)


In [ ]:

import numpy as np
Z=np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Exercise-4( How to get the documentation of the numpy add function from the command line?)

In [ ]:

import numpy
numpy.info(numpy.multiply) 

multiply(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Multiply arguments element-wise.

Parameters
----------
x1, x2 : array_like
    Input arrays to be multiplied.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the 

Exercise-5(Create a null vector of size 10 but the fifth value which is 1)

In [ ]:
Z = np.zeros(10) 
Z[4] = 1 
print(Z) 


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Exercise-6(Create a vector with values ranging from 10 to 49)

In [ ]:
import numpy as np
Z = np.arange(10,50) 
print(Z) 


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Exercise-7(Reverse a vector (first element becomes last))

In [ ]:
Z = np.arange(50) 
Z = Z[::-1] 
print(Z)



[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


Exercise-8(Create a 3x3 matrix with values ranging from 0 to 8)


In [ ]:
Z = np.arange(9).reshape(3,3) 
print(Z) 


[[0 1 2]
 [3 4 5]
 [6 7 8]]


Exercise-9(find indices of non zero elements)

In [ ]:
nz = np.nonzero([1,2,0,0,4,0]) 
print(nz) 


(array([0, 1, 4]),)


Exercise-10(Create a 3x3 identity matrix )

In [ ]:
Z = np.eye(3) 
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Exercise-11( Create a 3x3x3 array with random values)

In [ ]:
import numpy as np
Z=np.random.random((3,3,3)) 
print(Z) 


[[[0.80202293 0.80876269 0.18143178]
  [0.33394415 0.03208736 0.18860213]
  [0.47035449 0.47052116 0.68938311]]

 [[0.91919107 0.5086596  0.88574746]
  [0.84258907 0.14785515 0.76929852]
  [0.76127353 0.80392831 0.39659248]]

 [[0.76460804 0.21044928 0.85778232]
  [0.59934021 0.45548772 0.76080812]
  [0.6466748  0.47895726 0.69081666]]]


Exercise-12(Create a 10x10 array with random values and find the minimum and maximum values)

In [ ]:
import numpy as np
Z = np.random.random((10,10)) 
Zmin, Zmax = Z.min(), Z.max() 
print(Zmin, Zmax)
print(Z) 


0.004270995304508585 0.9983964760715762
[[0.60832949 0.25357725 0.97269142 0.85477444 0.79542388 0.34154829
  0.72226148 0.19212795 0.38494376 0.86872622]
 [0.35111516 0.49757423 0.27456227 0.73696696 0.7942998  0.75758442
  0.72112761 0.38891296 0.84849022 0.77281783]
 [0.27774582 0.84560977 0.53248596 0.30538608 0.55448536 0.959554
  0.00501174 0.5834073  0.63690461 0.14329468]
 [0.69699687 0.83610631 0.29691852 0.80771908 0.4945647  0.41729826
  0.66166953 0.35872249 0.72879932 0.99839648]
 [0.92287424 0.77024196 0.81636239 0.0452964  0.004271   0.04470878
  0.83349525 0.24757267 0.58401174 0.20995292]
 [0.04181433 0.234059   0.09490047 0.45387161 0.38134428 0.2038362
  0.135633   0.5090819  0.82731162 0.35302228]
 [0.93379462 0.66694032 0.60944083 0.12394306 0.12177343 0.23565229
  0.31836858 0.8341601  0.23697261 0.60057798]
 [0.70987654 0.36668391 0.35087694 0.61071998 0.54312257 0.04278643
  0.47041422 0.71490866 0.75648253 0.39136664]
 [0.05441336 0.92602543 0.44155226 0.993876

Exercise-13(Create a random vector of size 30 and find the mean value )

In [ ]:
import numpy as np
Z = np.random.random(30) 
m = Z.mean() 
print(m)
 


0.491137172539822


Exercise-14(Create a 2d array with 1 on the border and 0 inside)

In [ ]:
import numpy as np
Z = np.ones((10,10)) 
Z[1:-1,1:-1] = 0
print(Z) 


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Exercise-15(What is the result of the following expression?)

In [ ]:

import numpy as np
0 * np.nan 
np.nan == np.nan 
np.inf > np.nan 
np.nan - np.nan 
0.3 == 3 * 0.1 




False

Exercise-16( Create a 5x5 matrix with values 1,2,3,4 just below the diagonal )

In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z) 


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Exercise-17(Create a 8x8 matrix and fill it with a checkerboard pattern)

In [ ]:
Z = np.zeros((8,8),dtype=int) 
Z[1::2,::2] = 1 
Z[::2,1::2] = 1 
print(Z) 


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Exercise-18(Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?)

In [ ]:
print(np.unravel_index(100,(6,7,8))) 


(1, 5, 4)


Exercise-19(Create a checkerboard 8x8 matrix using the tile function)

In [ ]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4)) 
print(Z) 


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Exercise-20(Normalize a 5x5 random matrix)

In [ ]:
Z = np.random.random((5,5)) 
Zmax, Zmin = Z.max(), Z.min() 
Z = (Z - Zmin)/(Zmax - Zmin) 
print(Z) 


[[0.80018604 0.55954714 0.48927762 0.6785883  0.86059343]
 [0.6620929  0.76499585 0.04633267 1.         0.35917546]
 [0.35463478 0.06723675 0.08750303 0.81072978 0.84923778]
 [0.74360092 0.86402421 0.         0.04104223 0.40930823]
 [0.93817363 0.16867686 0.5203128  0.90029301 0.63268383]]


Exercise-22

In [ ]:
Z = np.dot(np.ones((5,3)), np.ones((3,2))) 
print(Z) 



[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


Exercise-23

In [ ]:
import numpy as np
Z = np.arange(11) 
Z[(3 < Z) & (Z <= 8)] *= -1 
print(Z)


[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


Exercise-24

In [ ]:
print(sum(range(5),-1)) 
from numpy import * 
print(sum(range(5),-1))


9
10


Exercise-25

In [ ]:
Z=int(input("enter the number"))
Z**Z 
2 << Z >> 2 
Z <- Z 
1j*Z 
Z/1/1 
Z<Z>Z 


enter the number5


False

Exercise-26

In [ ]:
np.array(0) // np.array(0) 
np.array(0) // np.array(0.) 
np.array(0) / np.array(0) 
np.array(0) / np.array(0.) 


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in floor_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


nan

Exercise-27

In [ ]:
Z = np.random.uniform(-10,+10,10) 
print (np.trunc(Z + np.copysign(0.5, Z))) 


[ 1.  0.  4. -3. -1.  7.  4.  7. -7.  3.]


Exercise-28

In [ ]:
Z = np.random.uniform(0,10,10) 
print (Z - Z%1) 
print (np.floor(Z)) 
print (np.ceil(Z)-1)


[6. 7. 9. 6. 5. 9. 7. 7. 4. 6.]
[6. 7. 9. 6. 5. 9. 7. 7. 4. 6.]
[6. 7. 9. 6. 5. 9. 7. 7. 4. 6.]


Exercise-29

In [ ]:
Z = np.zeros((5,5)) 
Z += np.arange(5) 
print(Z) 


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Exercise-31

In [ ]:
import numpy as np
Z = np.linspace(0,1,12,endpoint=True)[1:-1] 
print(Z) 


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


Exercise-32

In [ ]:
Z = np.random.random(10) 
Z.sort() 
print(Z) 


[0.02072971 0.03072426 0.03640982 0.10193076 0.20406041 0.2220725
 0.30402105 0.38130959 0.48314583 0.79478047]


Exercise-33

In [ ]:
Z = np.arange(10) 
np.add.reduce(Z)

45

Exercise-34

In [ ]:
A = np.random.randint(0,2,5) 
B = np.random.randint(0,2,5) 
equal = np.allclose(A,B) 
print(equal) 


False


Exercise-35

In [ ]:
Z = np.zeros(10) 
Z.flags.writeable = False
Z[0]=1 
print(Z)



ValueError: ignored

Exercise-37

In [ ]:

import numpy as np
Z = np.random.random(10) 
Z[Z.argmax()] = 0 
print(Z)

[0.25560547 0.         0.57568465 0.06190483 0.49307194 0.72937085
 0.11369841 0.44885291 0.74498127 0.3085502 ]


Exercise-41

In [ ]:
import numpy as np
np.set_printoptions(threshold=np.nan) 
Z = np.zeros((25,25)) 
print(Z) 


ValueError: ignored

Exercise-42

In [ ]:
Z = np.arange(100) 
v = np.random.uniform(0,100) 
index = (np.abs(Z-v)).argmin() 
print(Z[index]) 


13
